steps:
 - name: maven:3.6.3-jdk-11
   entrypoint: mvn
   args: ['clean','package']

 - name: gcr.io/cloud-builders/docker
   args: ['build', '-t', 'us-central1-docker.pkg.dev/khushbu-419105/java-repo/javaimg:$SHORT_SHA','--build-arg=JAR_FILE=target/build-artifact', '.']
- images: ['us-central1-docker.pkg.dev/khushbu-419105/java-repo/javaimg::$SHORT_SHA']
   
options:
 logging: CLOUD_LOGGING_ONLY
 
