
  spring:
   datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: terraform-20240613124422788700000006.czhtyfllgyoa.us-east-1.rds.amazonaws.com:3306
     username: ctgdevops
     password: devops123
   jpa:
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
         dialect: org.hibernate.dialect.MySQL8Dialect
         format_sql: true
     show-sql: true
     

